name: Render Template

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.17.0'

    - name: Install dependencies
      run: go mod init example.com/template

    - name: Run template rendering
      run: go run main.go

    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-yaml
        path: output.yaml
